
name: E2E on Chrome

on: [push]

jobs:
  desktop:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome94-ff93
      # Fix issue https://github.com/cypress-io/github-action/issues/446
      options: --user 1001

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Install dependencies
      - name: Install Dependencies
        run: yarn
      # Runs cypress test coverage
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev
          wait-on: "http://localhost:3000"
          browser: chrome
          record: true
          parallel: false
          spec: cypress/integration/ui.spec.js
          config: baseUrl=http://localhost:3000,viewportWidth=1280,viewportHeight=800
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mobile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome94-ff93
      # Fix issue https://github.com/cypress-io/github-action/issues/446
      options: --user 1001

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Install dependencies
      - name: Install Dependencies
        run: yarn
      # Runs cypress test coverage
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev
          wait-on: "http://localhost:3000"
          browser: chrome
          record: true
          parallel: false
          spec: cypress/integration/ui.mobile.spec.js
          config: baseUrl=http://localhost:3000,viewportWidth=360,viewportHeight=760
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}